spring:
  datasource:
    # Perfil sp: PostgreSQL compartido.
    url: jdbc:postgresql://localhost:5432/stockrestaurante
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

